"""Curated public API for Platydiff."""

from platydiff._version import __version__
from platydiff.api import compare
from platydiff.core.models import (
    AutoCompareSpec,
    AutoResourceLimits,
    AutoTextOptions,
    BinaryCompareSpec,
    BinaryResourceLimits,
    BinarySpan,
    BytesSource,
    ChangeCompleteness,
    ChangeSelection,
    CompareOutcome,
    CompareOutcomeV2,
    CompareSpec,
    CompletedOutcome,
    CompletedOutcomeV2,
    DiagnosticSeverity,
    DiffResult,
    FailedOutcome,
    FailedOutcomeV2,
    Fidelity,
    MetricDirection,
    NewlinePolicy,
    PathSource,
    PluginHostExecutionRecord,
    ProviderIdentity,
    Relation,
    ResourceLimits,
    Source,
    SourceKind,
    TextCompareSpec,
    TextEncoding,
    TextSource,
    UnavailableOutcome,
    UnavailableOutcomeV2,
    Verdict,
)
from platydiff.core.serialization import upgrade_outcome_v1_to_v2
from platydiff.plugins import (
    PluginCatalogV1,
    PluginDiscoveryPolicy,
    PluginHost,
    discover_plugins,
)

__all__ = [
    "AutoCompareSpec",
    "AutoResourceLimits",
    "AutoTextOptions",
    "BinaryCompareSpec",
    "BinaryResourceLimits",
    "BinarySpan",
    "BytesSource",
    "ChangeCompleteness",
    "ChangeSelection",
    "CompareOutcome",
    "CompareOutcomeV2",
    "CompareSpec",
    "CompletedOutcome",
    "CompletedOutcomeV2",
    "DiagnosticSeverity",
    "DiffResult",
    "FailedOutcome",
    "FailedOutcomeV2",
    "Fidelity",
    "MetricDirection",
    "NewlinePolicy",
    "PathSource",
    "PluginCatalogV1",
    "PluginDiscoveryPolicy",
    "PluginHost",
    "PluginHostExecutionRecord",
    "ProviderIdentity",
    "Relation",
    "ResourceLimits",
    "Source",
    "SourceKind",
    "TextCompareSpec",
    "TextEncoding",
    "TextSource",
    "UnavailableOutcome",
    "UnavailableOutcomeV2",
    "Verdict",
    "__version__",
    "compare",
    "discover_plugins",
    "upgrade_outcome_v1_to_v2",
]
