"""Curated public API for Platydiff."""

from platydiff._version import __version__
from platydiff.api import compare
from platydiff.core.models import (
    AutoCompareSpec,
    AutoResourceLimits,
    AutoTextOptions,
    BinaryCompareSpec,
    BinaryResourceLimits,
    BytesSource,
    ChangeCompleteness,
    ChangeSelection,
    CompareOutcome,
    CompareSpec,
    CompletedOutcome,
    DiagnosticSeverity,
    DiffResult,
    FailedOutcome,
    Fidelity,
    MetricDirection,
    NewlinePolicy,
    PathSource,
    Relation,
    ResourceLimits,
    Source,
    SourceKind,
    TextCompareSpec,
    TextEncoding,
    TextSource,
    UnavailableOutcome,
    Verdict,
)

__all__ = [
    "AutoCompareSpec",
    "AutoResourceLimits",
    "AutoTextOptions",
    "BinaryCompareSpec",
    "BinaryResourceLimits",
    "BytesSource",
    "ChangeCompleteness",
    "ChangeSelection",
    "CompareOutcome",
    "CompareSpec",
    "CompletedOutcome",
    "DiagnosticSeverity",
    "DiffResult",
    "FailedOutcome",
    "Fidelity",
    "MetricDirection",
    "NewlinePolicy",
    "PathSource",
    "Relation",
    "ResourceLimits",
    "Source",
    "SourceKind",
    "TextCompareSpec",
    "TextEncoding",
    "TextSource",
    "UnavailableOutcome",
    "Verdict",
    "__version__",
    "compare",
]
