"""Public, versioned declarations for third-party Platydiff plugins.

Importing this module never enumerates or loads installed plugins.
"""

from platydiff.plugin_sdk._models import (
    HOST_FEATURES_V1,
    PLUGIN_API_MAJOR,
    PLUGIN_API_MINOR,
    PLUGIN_ENTRY_POINT_GROUP,
    PLUGIN_MANIFEST_SCHEMA_VERSION,
    CapabilityAvailabilityV1,
    CapabilityDeclarationV1,
    CapabilityHandleV1,
    CapabilityKind,
    ComparatorHandleV1,
    ComparatorRunV1,
    ComponentDeclarationV1,
    ComponentKind,
    DetectorCandidateV1,
    DetectorHandleV1,
    DetectorInputV1,
    PluginComparisonV1,
    PluginErrorV1,
    PluginExecutionErrorV1,
    PluginManifestFactoryV1,
    PluginManifestV1,
    PluginResourceLimitErrorV1,
    PluginUnavailableErrorV1,
    RuntimeDependencyV1,
    SourceServiceV1,
)

__all__ = [
    "HOST_FEATURES_V1",
    "PLUGIN_API_MAJOR",
    "PLUGIN_API_MINOR",
    "PLUGIN_ENTRY_POINT_GROUP",
    "PLUGIN_MANIFEST_SCHEMA_VERSION",
    "CapabilityAvailabilityV1",
    "CapabilityDeclarationV1",
    "CapabilityHandleV1",
    "CapabilityKind",
    "ComparatorHandleV1",
    "ComparatorRunV1",
    "ComponentDeclarationV1",
    "ComponentKind",
    "DetectorCandidateV1",
    "DetectorHandleV1",
    "DetectorInputV1",
    "PluginComparisonV1",
    "PluginErrorV1",
    "PluginExecutionErrorV1",
    "PluginManifestFactoryV1",
    "PluginManifestV1",
    "PluginResourceLimitErrorV1",
    "PluginUnavailableErrorV1",
    "RuntimeDependencyV1",
    "SourceServiceV1",
]
